--daemonize=false
--pid_file=pids/nebula-graphd.pid
--enable_optimizer=true
--default_charset=utf8
--default_collate=utf8_bin
--local_config=true
--log_dir=logs
--minloglevel=0
--v=0
--meta_server_addrs=nebula-metad:9559
--local_ip=nebula
--port=9669
--ws_ip=0.0.0.0
--ws_http_port=19669
--enable_authorize=false