--daemonize=false
--pid_file=pids/nebula-storaged.pid
--local_config=true
--log_dir=logs
--minloglevel=0
--v=0
--meta_server_addrs=nebula-metad:9559
--local_ip=nebula-storaged
--port=9779
--ws_ip=0.0.0.0
--ws_http_port=19779
--data_path=/data/storage