import asyncio
import json

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse

from app.models.schemas import QueryRequest, QueryResponse, SourceInfo, SourceTriplet
from app.pipelines.query import (
    _compute_confidence,
    _fuse_context,
    search_similar_triplets,
    stream_answer,
    traverse_graph,
)
from app.pipelines.query import query as query_pipeline

router = APIRouter(prefix="/api/v1", tags=["query"])


@router.post(
    "/query",
    response_model=QueryResponse,
    summary="Ask a question",
    description="Submit a question to the GraphRAG system. The question is embedded, "
    "similar triplets retrieved from Qdrant, context expanded via NebulaGraph traversal, "
    "and an answer generated by the LLM. Supports scope filtering by system, account_id, etc.",
    responses={
        200: {"description": "Answer generated successfully"},
        503: {"description": "Backend service unavailable"},
    },
)
async def query_endpoint(request: QueryRequest):
    try:
        filters = dict(request.filters) if request.filters else {}
        scope = dict(request.scope) if request.scope else {}
        if request.account_id:
            scope["account_id"] = request.account_id
        if request.tenant_id:
            scope["tenant_id"] = request.tenant_id
        if request.user_id:
            scope["user_id"] = request.user_id
        return query_pipeline(
            question=request.question,
            top_k=request.top_k,
            min_score=request.min_score,
            filters=filters or None,
            scope=scope or None,
            active_only=request.active_only,
        )
    except Exception as e:
        raise HTTPException(
            status_code=503,
            detail=f"Error processing query: {str(e)}",
        )


@router.post(
    "/query/stream",
    summary="Ask a question with streaming response",
    description="Same as /query but streams the LLM response token-by-token using SSE. "
    "Sends metadata first, then tokens, then DONE signal.",
    responses={
        200: {"description": "Streaming response with structured events"},
        503: {"description": "Backend service unavailable"},
    },
)
async def query_stream_endpoint(request: QueryRequest):
    try:
        filters = dict(request.filters) if request.filters else {}
        scope = dict(request.scope) if request.scope else {}
        if request.account_id:
            scope["account_id"] = request.account_id
        if request.tenant_id:
            scope["tenant_id"] = request.tenant_id
        if request.user_id:
            scope["user_id"] = request.user_id

        vector_results = search_similar_triplets(
            request.question,
            top_k=request.top_k,
            min_score=request.min_score,
            filters=filters or None,
            scope=scope or None,
            active_only=request.active_only,
        )

        entity_ids = list(
            {r.subject_id for r in vector_results if r.subject_id}
            | {r.object_id for r in vector_results if r.object_id}
        )

        graph_results = traverse_graph(entity_ids, hop_depth=1)

        context, fused_results = await asyncio.to_thread(_fuse_context, vector_results, graph_results)

        if not context.strip():
            context = "No relevant context found."

        # Prepare metadata
        entities_found = list(
            {r.subject for r in fused_results if r.subject} | {r.object for r in fused_results if r.object}
        )

        confidence = _compute_confidence(vector_results, len(fused_results))

        # Build sources using Pydantic models for type safety
        sources_by_chunk: dict[str, SourceInfo] = {}
        for r in vector_results:
            chunk_id = r.chunk_id or "unknown"
            if chunk_id not in sources_by_chunk:
                sources_by_chunk[chunk_id] = SourceInfo(
                    chunk_id=chunk_id,
                    document=r.source_doc,
                    triplets=[],
                )
            sources_by_chunk[chunk_id].triplets.append(
                SourceTriplet(subject=r.subject, predicate=r.predicate, object=r.object)
            )

        metadata = {
            "type": "metadata",
            "confidence": confidence,
            "entities": entities_found,
            "sources": [s.model_dump() for s in sources_by_chunk.values()],
        }

        async def event_stream():
            # Send metadata first
            yield f"data: {json.dumps(metadata)}\n\n"

            # Stream tokens
            for token in stream_answer(request.question, context):
                token_event = {"type": "token", "content": token}
                yield f"data: {json.dumps(token_event)}\n\n"

            # Send completion signal
            yield f"data: {json.dumps({'type': 'done'})}\n\n"

        return StreamingResponse(event_stream(), media_type="text/event-stream")
    except Exception as e:
        raise HTTPException(
            status_code=503,
            detail=f"Error processing query: {str(e)}",
        )
