from fastapi import APIRouter, HTTPException

from app.models.schemas import QueryRequest, QueryResponse
from app.pipelines.query import query as query_pipeline

router = APIRouter(prefix="/api/v1", tags=["query"])


@router.post(
    "/query",
    response_model=QueryResponse,
    summary="Ask a question",
    description="Submit a question to the GraphRAG system. The question is embedded, "
    "similar triplets retrieved from Qdrant, context expanded via NebulaGraph traversal, "
    "and an answer generated by the LLM.",
    responses={
        200: {"description": "Answer generated successfully"},
        503: {"description": "Backend service unavailable"},
    },
)
async def query_endpoint(request: QueryRequest):
    try:
        return query_pipeline(request.question, request.top_k)
    except Exception as e:
        raise HTTPException(
            status_code=503,
            detail=f"Error processing query: {str(e)}",
        )
